apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-jenkins
  namespace: jenkins-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-jenkins
  template:
    metadata:
      labels:
        app: server-jenkins
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      serviceAccountName: jenkins # user admin-jenkins previously
      containers:
        - name: deployment-jenkins
          image: mokadir/jenkins:lts-jdk21
          env:
            - name: DOCKER_HOST
              value: "tcp://docker:2376"
            - name: DOCKER_CERT_PATH
              value: "/certs/client" # "/etc/docker/certificates/server" #"/certs/client"
            - name: DOCKER_TLS_VERIFY
              value: "1"
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - name: httpport
              containerPort: 8080
            - name: jnlpport
              containerPort: 50000
          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: data-jenkins
              mountPath: /var/jenkins_home
            - name: jenkins-docker-certs
              mountPath: /certs/client #/etc/docker/certificates/server
              readOnly: true
      volumes:
        - name: data-jenkins
          persistentVolumeClaim:
            claimName: pvc-jenkins
